# Generated by Django 5.0 on 2024-10-29 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('sport_name', models.CharField(max_length=50, verbose_name='競技名')),
                ('game_date', models.DateTimeField(verbose_name='試合日')),
                ('release_date', models.DateTimeField(verbose_name='発売日')),
                ('opponent_team', models.CharField(max_length=100, verbose_name='対戦相手')),
                ('place', models.CharField(max_length=100, verbose_name='会場')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-game_date'],
                'unique_together': {('sport_name', 'game_date', 'opponent_team')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_count', models.PositiveIntegerField(default=0, verbose_name='重複枚数')),
                ('order_number', models.CharField(default='', max_length=50, verbose_name='購入識別番号')),
                ('quantity', models.PositiveIntegerField(verbose_name='購入枚数')),
                ('purchase_datetime', models.DateTimeField(verbose_name='購入日時')),
                ('ticket_type', models.CharField(max_length=50, verbose_name='チケット種類')),
                ('ticket_price', models.PositiveIntegerField(verbose_name='チケット価格')),
                ('seat_type', models.CharField(max_length=50, verbose_name='座席種')),
                ('coupon_applied', models.BooleanField(default=False, verbose_name='クーポン有無')),
                ('category', models.CharField(choices=[('筑波大生', '筑波大生'), ('筑波大教職員', '筑波大教職員'), ('つくば市在住', 'つくば市在住'), ('つくば市在勤', 'つくば市在勤'), ('卒業生', '卒業生'), ('その他', 'その他')], max_length=50, verbose_name='カテゴリー')),
                ('nationality', models.CharField(max_length=50, verbose_name='国籍')),
                ('gender', models.CharField(choices=[('男性', '男性'), ('女性', '女性'), ('その他', 'その他'), ('無回答', '無回答')], max_length=50, verbose_name='性別')),
                ('age_group', models.CharField(choices=[('18歳以下', '18歳以下'), ('19&20代', '19&20代'), ('30代', '30代'), ('40代', '40代'), ('50代', '50代'), ('60代', '60代'), ('70代以上', '70代以上')], max_length=50, verbose_name='年代')),
                ('school_year', models.CharField(choices=[('1年', '1年'), ('2年', '2年'), ('3年', '3年'), ('4年', '4年'), ('Master', 'Master'), ('Ph.D', 'Ph.D'), ('他大生', '他大生'), ('筑波大生でない', '筑波大生でない')], max_length=50, verbose_name='学年')),
                ('department', models.CharField(choices=[('筑波大生でない', '筑波大生でない'), ('人文・文化学群', '人文・文化学群'), ('社会・国際学群', '社会・国際学群'), ('人間学群', '人間学群'), ('生命環境学群', '生命環境学群'), ('理工学群', '理工学群'), ('情報学群', '情報学群'), ('医学群', '医学群'), ('体育専門学群', '体育専門学群'), ('芸術専門学群', '芸術専門学群'), ('総合学域群', '総合学域群'), ('人文社会ビジネス科学学術院', '人文社会ビジネス科学学術院'), ('理工情報生命学術院', '理工情報生命学術院'), ('人間総合科学学術院', '人間総合科学学術院'), ('グローバル教育院', 'グローバル教育院')], max_length=50, verbose_name='所属')),
                ('referral_source', models.CharField(max_length=50, verbose_name='流入経路')),
                ('attendance_count', models.CharField(choices=[('0', '0'), ('1~2', '1~2'), ('3~4', '3~4'), ('5~6', '5~6'), ('7~', '7~')], max_length=50, verbose_name='来場回数')),
                ('play_freq', models.CharField(choices=[('3回+/週', '3回+/週'), ('1~2回/週', '1~2回/週'), ('1回/月', '1回/月'), ('1回/2~3カ月', '1回/2~3カ月'), ('1回-/2~3カ月', '1回-/2~3カ月')], max_length=50, verbose_name='スポーツ実施頻度')),
                ('viewing_freq', models.CharField(choices=[('3+回/週', '3+回/週'), ('1~2回/週', '1~2回/週'), ('24~36回/年', '24~36回/年'), ('12回/年', '12回/年'), ('4~6回/年', '4~6回/年'), ('2回/年', '2回/年'), ('1回/年', '1回/年'), ('1-回/年', '1-回/年')], max_length=50, verbose_name='スポーツ観戦観戦頻度')),
                ('special_viewing_freq', models.CharField(choices=[('3+回/週', '3+/週'), ('1~2回/週', '1~2回/週'), ('24~36回/年', '24~36回/年'), ('12回/年', '12回/年'), ('4~6回/年', '4~6回/年'), ('2回/年', '2回/年'), ('1回/年', '1回/年'), ('1-回/年', '1-回/年')], max_length=50, verbose_name='開催競技観戦頻度')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.event')),
            ],
        ),
    ]
