# Generated by Django 5.0 on 2024-10-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_ticket_count_alter_ticket_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='age_group',
            field=models.CharField(choices=[('18歳以下', '18歳以下'), ('19&20代', '19&20代'), ('30代', '30代'), ('40代', '40代'), ('50代', '50代'), ('60代', '60代'), ('70代以上', '70代以上'), ('無回答', '無回答')], default='無回答', max_length=50, verbose_name='年代'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attendance_count',
            field=models.CharField(choices=[('0', '0'), ('1~2', '1~2'), ('3~4', '3~4'), ('5~6', '5~6'), ('7~', '7~'), ('無回答', '無回答')], default='無回答', max_length=50, verbose_name='来場回数'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('筑波大生', '筑波大生'), ('筑波大教職員', '筑波大教職員'), ('つくば市在住', 'つくば市在住'), ('つくば市在勤', 'つくば市在勤'), ('卒業生', '卒業生'), ('その他', 'その他'), ('無回答', '無回答')], default='無回答', max_length=50, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('筑波大生でない', '筑波大生でない'), ('人文・文化学群', '人文・文化学群'), ('社会・国際学群', '社会・国際学群'), ('人間学群', '人間学群'), ('生命環境学群', '生命環境学群'), ('理工学群', '理工学群'), ('情報学群', '情報学群'), ('医学群', '医学群'), ('体育専門学群', '体育専門学群'), ('芸術専門学群', '芸術専門学群'), ('総合学域群', '総合学域群'), ('人文社会ビジネス科学学術院', '人文社会ビジネス科学学術院'), ('理工情報生命学術院', '理工情報生命学術院'), ('人間総合科学学術院', '人間総合科学学術院'), ('グローバル教育院', 'グローバル教育院'), ('無回答', '無回答')], default='無回答', max_length=50, verbose_name='所属'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='gender',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性'), ('その他', 'その他'), ('無回答', '無回答')], default='無回答', max_length=50, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='play_freq',
            field=models.CharField(choices=[('3回+/週', '3回+/週'), ('1~2回/週', '1~2回/週'), ('1回/月', '1回/月'), ('1回/2~3カ月', '1回/2~3カ月'), ('1回-/2~3カ月', '1回-/2~3カ月'), ('無回答', '無回答')], default='無回答', max_length=50, verbose_name='スポーツ実施頻度'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='special_viewing_freq',
            field=models.CharField(choices=[('3+回/週', '3+/週'), ('1~2回/週', '1~2回/週'), ('24~36回/年', '24~36回/年'), ('12回/年', '12回/年'), ('4~6回/年', '4~6回/年'), ('2回/年', '2回/年'), ('1回/年', '1回/年'), ('1-回/年', '1-回/年'), ('無回答', '無回答')], default='無回答', max_length=50, verbose_name='開催競技観戦頻度'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='viewing_freq',
            field=models.CharField(choices=[('3+回/週', '3+回/週'), ('1~2回/週', '1~2回/週'), ('24~36回/年', '24~36回/年'), ('12回/年', '12回/年'), ('4~6回/年', '4~6回/年'), ('2回/年', '2回/年'), ('1回/年', '1回/年'), ('1-回/年', '1-回/年'), ('無回答', '無回答')], default='無回答', max_length=50, verbose_name='スポーツ観戦観戦頻度'),
        ),
    ]
