# Generated by Django 5.1.3 on 2024-11-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_age_group_alter_ticket_attendance_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='school_year',
            new_name='grade',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='referral_source',
            field=models.CharField(max_length=150, verbose_name='流入経路'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='viewing_freq',
            field=models.CharField(choices=[('3+回/週', '3+回/週'), ('1~2回/週', '1~2回/週'), ('24~36回/年', '24~36回/年'), ('12回/年', '12回/年'), ('4~6回/年', '4~6回/年'), ('2回/年', '2回/年'), ('1回/年', '1回/年'), ('1-回/年', '1-回/年'), ('無回答', '無回答')], default='無回答', max_length=50, verbose_name='スポーツ観戦頻度'),
        ),
    ]
