# Generated by Django 5.1.3 on 2024-11-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_school_year_ticket_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='grade',
            field=models.CharField(choices=[('1年', '1年'), ('2年', '2年'), ('3年', '3年'), ('4年', '4年'), ('Master', 'Master'), ('Ph.D', 'Ph.D'), ('他大生', '他大生'), ('筑波大生でない', '筑波大生でない'), ('無回答', '無回答')], max_length=50, verbose_name='学年'),
        ),
    ]
